# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  database:
    :password: password
  secret_key_base: 422bf3b39de37858e3de86dc8a0c90c3f95f4d02ac5ff2cfcc1d1fd1d0a9af42228e0b6fb0ca09e38d7f718ec5a38990934dd00a42b40432e73cb93920cf9534

test:
  database:
    :password: password
  secret_key_base: fc4e09be12a9dd2076515068274e7b2ea48094ea64d81a10256ad0df1fbc799939b94fc69bbf52ed76e9aeaadf1648e5c420e6ccbd1e2b82979d1d1cfbf0ec15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  database:
    :password: <%= ENV["PRODUCTION_DATABASE_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
